# Python Libraries Interactive Notebook

Today, we will be learning about 4 fundamental python libraries: numpy, matplotlib, pandas, and seaborn. Note that these are widely used and documentaion can be found online for each library. Or search Google/Stack Overflow!
- Numpy: https://docs.scipy.org/doc/numpy-dev/user/index.html
- Pandas: http://pandas.pydata.org/pandas-docs/stable/
- Matplotlib: https://matplotlib.org/2.1.2/index.html
- Seaborn: https://seaborn.pydata.org/

### Jupyter Notebook Recap

```To run a cell: select cell, press SHIFT + ENTER```

The last line of a cell is always printed out. Or use print.

In [9]:
"this won't be displayed"
"this will be displayed"

'this will be displayed'

## Import

```pandas```, ```numpy```, ```matpotlib```, and ```seaborn``` are python modules created by other people that are widely used in the 'real world' and make working with Data possible in python. Whenever you want to use them, remember to ```import``` the necessary module first.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

# <span style="color: blue">Numpy</span>

Numpy's main use is ```np.array```

Numpy arrays take less space than built-in lists and come with a **wide variety of useful functions.**

In [11]:
# make an array
a = np.array([2,3,4])
a

array([2, 3, 4])

In [15]:
# make a 2-dimensional array (matrix)
matrix = np.array([ [1,2,3],
                    [4,5,6],
                    [7,8,9] ])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# you can multiply matrices with np.dot
np.dot(matrix, a)

array([20, 47, 74])

### Arithmetic with numpy!

You can add/subtract/multiply/divide with arrays.

In [39]:
a + 5

array([7, 8, 9])

In [24]:
a * -1

array([-2, -3, -4])

In [41]:
b = np.array([3, 2, 1])
a + b

array([5, 5, 5])

If you try to perform operations on two arrays of different lengths, <span style="color:red">an error will occur.</span> Try running the following cell!

In [43]:
# Run me!
b + np.array([1, 2, 3, 4])

Use ```len( array )``` to find length of array.

In [44]:
len(b)

3

In [45]:
len(np.array([1, 2, 3, 4]))

4

### Essential array functions

In [34]:
np.sum(a)

9

In [35]:
np.min(a)

2

In [36]:
np.max(a)

4

In [37]:
np.mean(a)

3.0

### Python

We can still use ```np.arrays``` in the same way we used built-in python lists.

In [53]:
a

array([2, 3, 4])

In [55]:
cumulative_product = 1

for element in a:
    cumulative_product *= element
    
cumulative_product

24


# ```include quick practice probs here...```

# <span style="color: blue">Pandas</span>

<img width=100 src="https://c402277.ssl.cf1.rackcdn.com/photos/13100/images/featured_story/BIC_128.png?1485963152"/>For Pandas, its main function use is **tables**!

A [dataframe](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dataframe) is a table in Pandas

In [56]:
fruit_info = pd.DataFrame(
    data={'fruit': ['apple', 'orange', 'banana', 'raspberry'],
          'color': ['red', 'orange', 'yellow', 'pink']
          })
fruit_info

color      fruit
0     red      apple
1  orange     orange
2  yellow     banana
3    pink  raspberry

# <span style="color: blue">Matplotlib</span>


# <span style="color: blue">Seaborn</span>
